- Controller/src/LSST/M1M3/SS/Accelerometer/AccelerometerSettings.cpp
- Controller/src/LSST/M1M3/SS/Displacement/DisplacementSensorSettings.cpp
- Controller/src/LSST/M1M3/SS/Gyro/GyroSettings.cpp
- Controller/src/LSST/M1M3/SS/Inclinometer/InclinometerSettings.cpp
- Controller/src/LSST/M1M3/SS/Logging/Logger.h
- Controller/src/LSST/M1M3/SS/Settings/AliasApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/ExpansionFPGAApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/ForceActuatorApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/ForceActuatorSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/HardpointActuatorApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/HardpointActuatorSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/HardpointMonitorApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/ILCApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/InterlockApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/PIDSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/PositionControllerSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/RecommendedApplicationSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/SafetyControllerSettings.cpp
- Controller/src/LSST/M1M3/SS/Settings/SettingReader.cpp
- Controller/src/LSST/M1M3/SS/Settings/SettingReader.h
See: https://jira.lsstcorp.org/browse/DM-22413
> Add error handling to XML parsing when loading setting files

- Controller/src/LSST/M1M3/SS/PID/PID.cpp
See https://jira.lsstcorp.org/browse/DM-22688 and https://jira.lsstcorp.org/browse/DM-22621.
> DM-22688: mitigates change in ts_xml

- CentOS/makefile
- src/LSST/M1M3/SS/CommandFactory/CommandFactory.cpp
- src/LSST/M1M3/SS/Commands/TMAAzimuthSampleCommand.cpp
- src/LSST/M1M3/SS/Commands/TMAAzimuthSampleCommand.h
- src/LSST/M1M3/SS/Commands/TMAElevationSampleCommand.cpp
- src/LSST/M1M3/SS/Commands/TMAElevationSampleCommand.h
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/FirmwareUpdate/FirmwareUpdate.h
- src/LSST/M1M3/SS/ForceController/ForceController.cpp
- src/LSST/M1M3/SS/ForceController/ForceController.h
- src/LSST/M1M3/SS/States/EnabledState.cpp
- src/LSST/M1M3/SS/Subscriber/M1M3SSSubscriber.cpp
- src/LSST/M1M3/SS/Subscriber/M1M3SSSubscriber.h
- src/ts_M1M3Support.cpp
Runs with current ts_xml schema (renamed Mount_AltC->Mount_ElevationC,..). Added -c argument for configuration path.
> Runs with current ts_xml, -c argument

- Jenkinsfile
- Makefile
- Makefile.inc
- src/LSST/M1M3/SS/Include/PIDParameters.h
- src/LSST/M1M3/SS/PID/PID.cpp
- src/LSST/M1M3/SS/PID/PID.h
- src/Makefile
- tests/Makefile
- tests/test_PID.cpp
Basic PID tests using boost test API. Updated Makefiles, generate libM1M3 to
support faster linking of the test binaries. Added Jenkinsfile for CI tests.
> DM-25064: PID tests

- src/LSST/M1M3/SS/FPGA/FPGA.cpp
- src/LSST/M1M3/SS/FPGA/FPGA.h
- src/LSST/M1M3/SS/FPGA/IFPGA.h
- src/LSST/M1M3/SS/FPGA/NiFpga_M1M3SupportFPGA.h
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/FirmwareUpdate/FirmwareUpdate.cpp
- src/LSST/M1M3/SS/ILC/ILC.cpp
- src/LSST/M1M3/SS/Utility/ModbusBuffer.cpp
- src/LSST/M1M3/SS/Utility/ModbusBuffer.h
- src/cliapp/CliApp.hpp
- src/m1m3cli.cpp
- tests/test_ModbusBuffer.cpp
Improves handling of the ILC Info command - prints FPGA timestamps, add verbose
options. Improves error handling by raising error on errors.
> DM-24406: runs hardware simulator

- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
Make simulated pga listen for telescope position to emulate inclinometer.
> DM-25475: Implement M2 LUT behavior in m2 simulator

- src/LSST/M1M3/SS/Threads/ControllerThread.cpp
In previous version, the conditional wait was limited only to
_keepRunning and was set for a wrong variable. That was fixed by swapping
_keepRunning test and adding test for empty queue, which needs to be
performed.
> Properly wrap conditional waits in lock

- src/ts_M1M3Support.cpp
So log messages are properly identified.
> changed loggername to MTM1M3

- src/LSST/M1M3/SS/Controllers/BumpTestController.cpp
Better wording of message when FA bump test fails.
> add +- (\xb1) to messages

- src/LSST/M1M3/SS/Controllers/HardpointActuatorMotionStates.h
- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.cpp
- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.h
- src/LSST/M1M3/SS/Controllers/PositionController.h
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
Add messages about raising progress.
> Fix simulator response to encoder request

- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.h
- src/LSST/M1M3/SS/Settings/HardpointActuatorSettings.cpp
- src/LSST/M1M3/SS/Settings/HardpointActuatorSettings.h
- src/LSST/M1M3/SS/Settings/SettingReader.h
Both ILC code 66 (unicast set position) and code 67 (return status) returns
same value. Only one function is needed to parse ILC response. Changed
simulator response as well.
> Fixed HP response

- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/States/ActiveEngineeringState.cpp
Fixes translations parameters passing, simulator correctly reports end timestamps.
> Fixes translations parameters passing, simulator correctly reports end timestamps.

- src/LSST/M1M3/SS/States/ActiveEngineeringState.cpp
- src/LSST/M1M3/SS/States/ActiveEngineeringState.h
- src/LSST/M1M3/SS/States/ActiveState.cpp
- src/LSST/M1M3/SS/States/EnabledActiveState.cpp
- src/LSST/M1M3/SS/States/EnabledActiveState.h
- src/LSST/M1M3/SS/States/EngineeringState.cpp
- src/LSST/M1M3/SS/States/EngineeringState.h
- src/LSST/M1M3/SS/States/LoweringEngineeringState.cpp
- src/LSST/M1M3/SS/States/ParkedEngineeringState.cpp
- src/LSST/M1M3/SS/States/RaisingEngineeringState.cpp
EnabledActive state is a new parent of Active and ActiveEngineering states.
Allows for simple implementation of commands valid both in Active and
ActiveEngineering states.
> Commands for M1M3 Active State

- src/LSST/M1M3/SS/States/ActiveEngineeringState.h
- src/LSST/M1M3/SS/States/ActiveState.h
- src/LSST/M1M3/SS/States/EnabledActiveState.cpp
- src/LSST/M1M3/SS/States/EnabledActiveState.h
Correctly lower in non-engineering/engineering mode
> getLoweringState method

- Makefile
- Makefile.inc
Uses static libraries. Adds simulator target.
> Improved Makefile

- .gitignore
- src/LSST/M1M3/SS/Controllers/SafetyController.cpp
- src/LSST/M1M3/SS/States/LoweringFaultState.cpp
- src/LSST/M1M3/SS/States/LoweringFaultState.h
- tests/test_SafetyController.cpp
- tests/test_SafetyControllerSettings.cpp
Also reports failures in message log
> fix low air pressure logging

- Dockerfile
- Jenkinsfile
- SettingFiles/Sets/Default/1/SafetyControllerSettings.yaml
- src/LSST/M1M3/SS/Controllers/PositionController.cpp
- src/LSST/M1M3/SS/Controllers/PowerController.cpp
- src/LSST/M1M3/SS/DigitalInputOutput/DigitalInputOutput.cpp
- src/LSST/M1M3/SS/DigitalInputOutput/DigitalInputOutput.h
- src/LSST/M1M3/SS/FPGA/FPGAAddresses.h
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.h
- src/LSST/M1M3/SS/Include/AirControllerSafetySettings.h
- src/LSST/M1M3/SS/Utility/ModbusBuffer.cpp
- src/m1m3sscli.cpp
- hardpoint-force command
- setBit method, FPGA constants
- report mismatch after some time
- switched limit switch in hardpoints, fixed moving HP out of limits
- ValveTransitionPeriod, better debugging
> Fix various problems with safety controller

- Jenkinsfile
- src/LSST/M1M3/SS/Commands/KillHardpointTestCommand.cpp
- src/LSST/M1M3/SS/Commands/KillHardpointTestCommand.h
- src/LSST/M1M3/SS/Commands/TestHardpointCommand.cpp
- src/LSST/M1M3/SS/Context/Context.cpp
- src/LSST/M1M3/SS/Context/Context.h
- src/LSST/M1M3/SS/Controllers/BumpTestController.cpp
- src/LSST/M1M3/SS/Controllers/HardpointTestController.cpp
- src/LSST/M1M3/SS/Controllers/HardpointTestController.h
- src/LSST/M1M3/SS/Controllers/PositionController.cpp
- src/LSST/M1M3/SS/Controllers/PositionController.h
- src/LSST/M1M3/SS/Displacement/DisplacementSensorSettings.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/Model/Model.cpp
- src/LSST/M1M3/SS/Model/Model.h
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.cpp
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.h
- src/LSST/M1M3/SS/Settings/HardpointMonitorApplicationSettings.cpp
- src/LSST/M1M3/SS/Settings/SettingReader.cpp
- src/LSST/M1M3/SS/States/ParkedEngineeringState.cpp
- src/LSST/M1M3/SS/States/State.cpp
- src/LSST/M1M3/SS/States/State.h
- src/LSST/M1M3/SS/Subscriber/M1M3SSSubscriber.cpp
- src/LSST/M1M3/SS/Subscriber/M1M3SSSubscriber.h
- src/LSST/M1M3/SS/Threads/SubscriberThread.cpp
- testHardpoint and killHardpointTest commands
- _writeModbus[Float[16|32] methods
- simulate HP limit switches
- Fixed DisplacementSensorSettings issues
- PositionConroller::moveHardpoin
> DM-35863: HardpointTest command

- Dockerfile
- Makefile.inc
- src/LSST/M1M3/SS/DigitalInputOutput/DigitalInputOutput.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/Model/Model.cpp
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.cpp
- src/LSST/M1M3/SS/States/StandbyState.cpp
- src/LSST/M1M3/SS/Utility/ModbusBuffer.cpp
- src/Makefile
- src/ts-M1M3supportd.cpp
- Fix startup sequence, improves debugging data
- Print full dump of buffer with invalid CRC
- Better CRC error reporting
- Detect git version changes
> Fix startup issues, better version management

- SettingFiles/Sets/Default/v1/ForceActuatorSettings.yaml
- src/LSST/M1M3/SS/Controllers/ForceController.cpp
- src/LSST/M1M3/SS/Controllers/SafetyController.cpp
- src/LSST/M1M3/SS/Controllers/SafetyController.h
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/Utility/Range.h
- Detailed description on moment warnings
- Change active optics force limit, timestamp in FA SetpointWarning
> Improve warnings texts

- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.cpp
- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.h
- src/LSST/M1M3/SS/DigitalInputOutput/DigitalInputOutput.cpp
- src/LSST/M1M3/SS/DigitalInputOutput/DigitalInputOutput.h
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/Publisher/AirSupplyStatus.cpp
- src/LSST/M1M3/SS/Publisher/AirSupplyStatus.h
- src/LSST/M1M3/SS/Publisher/HardpointActuatorWarning.cpp
- src/LSST/M1M3/SS/Publisher/HardpointActuatorWarning.h
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.cpp
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.h
- Wait for air pressure before raising the mirror
- AirSupplyStatus class, checks for air valve opened/closed
> Wait for air pressure to build up before raising the mirror

- Jenkinsfile
- src/LSST/M1M3/SS/Controllers/ForceController.cpp
- src/LSST/M1M3/SS/Controllers/ForceController.h
- src/LSST/M1M3/SS/Controllers/MirrorLowerController.cpp
- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.cpp
- src/LSST/M1M3/SS/Controllers/PositionController.cpp
- src/LSST/M1M3/SS/Controllers/PositionController.h
- src/LSST/M1M3/SS/ForceComponents/ElevationForceComponent.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/Publisher/HardpointActuatorWarning.cpp
- src/LSST/M1M3/SS/Publisher/HardpointActuatorWarning.h
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.cpp
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.h
- src/LSST/M1M3/SS/Publisher/RaisingLoweringInfo.cpp
- src/LSST/M1M3/SS/Publisher/RaisingLoweringInfo.h
- src/LSST/M1M3/SS/States/FaultState.cpp
- tests/test_ForceController.cpp
- RaisingLoweringInfo event
- low/highAirPressureFault
- supportedPercentage -> weightSupportPercent
- waitAirPressure
- waitHardpoint
> RaisingLoweringInfo

- Jenkinsfile
- src/m1m3sscli.cpp
- RaisingLoweringInfo event
- low/highAirPressureFault
- supportedPercentage -> weightSupportPercent
- waitAirPressure
- waitHardpoint, wait[XYZ]ForceActuator
- SAA, DAA Force Status
- setDAA/SAAForceOffset
- air command
> CLI DAA and SAA offset commands, air valve control from m1m3sscli

- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
Report hardpoint limits in status for 65 and 67 ILC command.
> Fix simulator - reports HP end switches state

- Jenkinsfile
- SettingFiles/v1/_init.yaml
- src/LSST/M1M3/SS/Controllers/MirrorLowerController.cpp
- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.cpp
- src/LSST/M1M3/SS/Controllers/PositionController.cpp
- src/LSST/M1M3/SS/Controllers/PositionController.h
- src/LSST/M1M3/SS/Controllers/SafetyController.cpp
- src/LSST/M1M3/SS/Controllers/SafetyController.h
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/Include/FaultCodes.h
- src/LSST/M1M3/SS/Publisher/HardpointActuatorWarning.cpp
- src/LSST/M1M3/SS/Settings/HardpointActuatorSettings.cpp
- src/LSST/M1M3/SS/Settings/HardpointActuatorSettings.h
- src/LSST/M1M3/SS/Settings/PositionControllerSafetySettings.h
- src/LSST/M1M3/SS/Subscriber/TMA.h
- Raise mirror below 45 deg elevation
- wait_tension_t
- inRange counter, log messages
> Raise M1M3 at horizon

- Makefile
- Makefile.inc
- doc/version-history.rst
- init
- src/LSST/M1M3/SS/Accelerometer/Accelerometer.cpp
- src/LSST/M1M3/SS/Accelerometer/Accelerometer.h
- src/LSST/M1M3/SS/Commands/RawDCAccelerometersCommands.cpp
- src/LSST/M1M3/SS/Commands/RawDCAccelerometersCommands.h
- src/LSST/M1M3/SS/FPGA/FPGA.cpp
- src/LSST/M1M3/SS/FPGA/FPGA.h
- src/LSST/M1M3/SS/FPGA/IFPGA.h
- src/LSST/M1M3/SS/FPGA/SimulatedExpansionFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.h
- src/Makefile
- src/NiFpga/NiFpga_M1M3SupportFPGA.h
- src/m1m3sscli.cpp
- src/ts-M1M3supportd.cpp
- tests/Makefile
- utils/Makefile
- utils/dcrawdump.cpp
- accelerometer command in m1m3sscli
- Fixed version.c dependency, LIBS
- SIGUSR2 signal to start/stop raw data recordings
- Added dcrawdump
> DM-41983: dump raw DC accelerometer data

- doc/bump_test.md
- doc/version-history.rst
- src/LSST/M1M3/SS/Controllers/BumpTestController.cpp
- src/LSST/M1M3/SS/Controllers/BumpTestController.h
- Improved FA bump test documentation
- version entry, cRIOcpp changes
> DM-44265: document bump tests

- src/LSST/M1M3/SS/Model/Model.cpp
> DM-45927: Fill outerLoop timestamp

- doc/version-history.rst
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/ForceComponents/ForceComponent.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.h
- src/LSST/M1M3/SS/Publisher/ForceActuatorInfo.cpp
- src/LSST/M1M3/SS/Publisher/ForceActuatorInfo.h
Fixes problem with ILC calibration data readout.
> DM-46506: Fix ILC calibration data readout

- SettingFiles/v1/_init.yaml
- doc/version-history.rst
- src/LSST/M1M3/SS/Controllers/MirrorRaiseController.cpp
- src/LSST/M1M3/SS/Settings/ForceActuatorSettings.cpp
- src/LSST/M1M3/SS/States/ActiveEngineeringState.cpp
- src/LSST/M1M3/SS/States/ActiveEngineeringState.h
- src/LSST/M1M3/SS/States/EnabledActiveState.cpp
- src/LSST/M1M3/SS/States/EnabledActiveState.h
BalanceForcesOnInActiveState to automatically enable balance forces
after raise. Also balance forces can be commanded only in engineering
mode.
> BalanceForcesOnInActiveState

- doc/version-history.rst
- src/LSST/M1M3/SS/Commands/ForceActuatorBumpTestCommand.cpp
- src/LSST/M1M3/SS/ILC/ILCSubnetData.cpp
- src/LSST/M1M3/SS/Model/Model.cpp
- **Enable FAs not longer disabled in the configuration file**
- **Don't bump test disabled FAs**
> DM-48033: enable FAs from configuration file, don't bump test disabled FAs

- doc/version-history.rst
- src/LSST/M1M3/SS/Settings/ForceActuatorSettings.h
- src/m1m3sscli.cpp
- **Report pressure and force as M1M3 force actuator is active**
- **Test settings, test duration commands**
> DM-48025: daa-test and saa-test commands to record force and pressure as the FA is actuated

- doc/version-history.rst
- src/LSST/M1M3/SS/Controllers/BumpTestController.cpp
> Fix unicode +- (U00b1) characters.

- SettingFiles/v1/_init.yaml
- doc/version-history.rst
- src/LSST/M1M3/SS/Controllers/PositionController.cpp
- src/LSST/M1M3/SS/Controllers/PositionController.h
- src/LSST/M1M3/SS/Controllers/SafetyController.cpp
- src/LSST/M1M3/SS/Controllers/SafetyController.h
- src/LSST/M1M3/SS/DigitalInputOutput/DigitalInputOutput.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.cpp
- src/LSST/M1M3/SS/FPGA/SimulatedFPGA.h
- src/LSST/M1M3/SS/ILC/ILCResponseParser.cpp
- src/LSST/M1M3/SS/ILC/ILCResponseParser.h
- src/LSST/M1M3/SS/Model/Model.cpp
- src/LSST/M1M3/SS/Publisher/DetailedState.cpp
- src/LSST/M1M3/SS/Publisher/DetailedState.h
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.cpp
- src/LSST/M1M3/SS/Publisher/M1M3SSPublisher.h
- src/LSST/M1M3/SS/Settings/HardpointActuatorSettings.cpp
- src/LSST/M1M3/SS/Settings/PositionControllerSettings.cpp
Similar to change which resulted in ignoring excessive tension on HPs, ignore
excessive pressure.
> Ignore excessive pressure on HPs while the mirror is being raised.
